# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cwcs_s2p <- function(RA, Dec, CTYPE1 = "RA---TAN", CTYPE2 = "DEC--TAN", CRVAL1 = 0, CRVAL2 = 0, CRPIX1 = 0, CRPIX2 = 0, CD1_1 = 1, CD1_2 = 0, CD2_1 = 0, CD2_2 = 1, RADESYS = "ICRS", EQUINOX = 2000L, PV1_1 = NA_real_, PV1_2 = NA_real_, PV1_3 = NA_real_, PV2_1 = NA_real_, PV2_2 = NA_real_, PV2_3 = NA_real_, PV2_4 = NA_real_, PV2_5 = NA_real_) {
    .Call(`_Rwcs_Cwcs_s2p`, RA, Dec, CTYPE1, CTYPE2, CRVAL1, CRVAL2, CRPIX1, CRPIX2, CD1_1, CD1_2, CD2_1, CD2_2, RADESYS, EQUINOX, PV1_1, PV1_2, PV1_3, PV2_1, PV2_2, PV2_3, PV2_4, PV2_5)
}

Cwcs_p2s <- function(x, y, CTYPE1 = "RA---TAN", CTYPE2 = "DEC--TAN", CRVAL1 = 0, CRVAL2 = 0, CRPIX1 = 0, CRPIX2 = 0, CD1_1 = 1, CD1_2 = 0, CD2_1 = 0, CD2_2 = 1, RADESYS = "ICRS", EQUINOX = 2000L, PV1_1 = NA_real_, PV1_2 = NA_real_, PV1_3 = NA_real_, PV2_1 = NA_real_, PV2_2 = NA_real_, PV2_3 = NA_real_, PV2_4 = NA_real_, PV2_5 = NA_real_) {
    .Call(`_Rwcs_Cwcs_p2s`, x, y, CTYPE1, CTYPE2, CRVAL1, CRVAL2, CRPIX1, CRPIX2, CD1_1, CD1_2, CD2_1, CD2_2, RADESYS, EQUINOX, PV1_1, PV1_2, PV1_3, PV2_1, PV2_2, PV2_3, PV2_4, PV2_5)
}

Cwcs_head_p2s <- function(x, y, header, nkey, WCSref = 0L, ctrl = 2L) {
    .Call(`_Rwcs_Cwcs_head_p2s`, x, y, header, nkey, WCSref, ctrl)
}

Cwcs_head_s2p <- function(RA, Dec, header, nkey, WCSref = 0L, ctrl = 2L) {
    .Call(`_Rwcs_Cwcs_head_s2p`, RA, Dec, header, nkey, WCSref, ctrl)
}

.dilate_cpp <- function(segim, kern, expand = 0L) {
    .Call(`_Rwcs_dilate_cpp`, segim, kern, expand)
}

.num_mat_add_cpp <- function(base, add, ind, offset) {
    .Call(`_Rwcs_num_mat_add`, base, add, ind, offset)
}

.num_mat_add_mult_cpp <- function(base, add, mult, ind, offset) {
    .Call(`_Rwcs_num_mat_add_mult`, base, add, mult, ind, offset)
}

.int_mat_add_cpp <- function(base, add, ind, offset) {
    .Call(`_Rwcs_int_mat_add`, base, add, ind, offset)
}

.int_mat_add_sin_cpp <- function(base, add, ind, offset) {
    .Call(`_Rwcs_int_mat_add_sin`, base, add, ind, offset)
}

.stack_image_inVar_weight_mat_cpp <- function(post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset) {
    .Call(`_Rwcs_stack_image_inVar_weight_mat`, post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset)
}

.stack_image_inVar_weight_int_cpp <- function(post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset) {
    .Call(`_Rwcs_stack_image_inVar_weight_int`, post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset)
}

.stack_image_weight_mat_cpp <- function(post_image, post_weight, pre_image, pre_weight, offset) {
    .Call(`_Rwcs_stack_image_weight_mat`, post_image, post_weight, pre_image, pre_weight, offset)
}

.stack_image_weight_int_cpp <- function(post_image, post_weight, pre_image, pre_weight, offset) {
    .Call(`_Rwcs_stack_image_weight_int`, post_image, post_weight, pre_image, pre_weight, offset)
}

.stack_exp_cpp <- function(post_exp, pre_exp, offset) {
    .Call(`_Rwcs_stack_exp`, post_exp, pre_exp, offset)
}

.stack_image_inVar_weight_mat_mask_cpp <- function(post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset, post_mask) {
    .Call(`_Rwcs_stack_image_inVar_weight_mat_mask`, post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset, post_mask)
}

.stack_image_inVar_weight_int_mask_cpp <- function(post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset, post_mask) {
    .Call(`_Rwcs_stack_image_inVar_weight_int_mask`, post_image, post_inVar, post_weight, pre_image, pre_inVar, pre_weight, offset, post_mask)
}

.stack_image_weight_mat_mask_cpp <- function(post_image, post_weight, pre_image, pre_weight, offset, post_mask) {
    .Call(`_Rwcs_stack_image_weight_mat_mask`, post_image, post_weight, pre_image, pre_weight, offset, post_mask)
}

.stack_image_weight_int_mask_cpp <- function(post_image, post_weight, pre_image, pre_weight, offset, post_mask) {
    .Call(`_Rwcs_stack_image_weight_int_mask`, post_image, post_weight, pre_image, pre_weight, offset, post_mask)
}

.stack_exp_mask_cpp <- function(post_exp, pre_exp, offset, post_mask) {
    .Call(`_Rwcs_stack_exp_mask`, post_exp, pre_exp, offset, post_mask)
}

.mat_diff_sum <- function(mat1, mat2, scale = 1, delta_x = 0L, delta_y = 0L) {
    .Call(`_Rwcs_mat_diff_sum`, mat1, mat2, scale, delta_x, delta_y)
}

.pnpoly <- function(testx, testy, vertx, verty) {
    .Call(`_Rwcs_pnpoly`, testx, testy, vertx, verty)
}

