# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cwcs_s2p <- function(RA, Dec, CTYPE1, CTYPE2, CRVAL1 = 0, CRVAL2 = 0, CRPIX1 = 0, CRPIX2 = 0, CD1_1 = 1, CD1_2 = 0, CD2_1 = 0, CD2_2 = 1, PV1 = 0, PV2 = 0) {
    .Call(`_Rwcs_Cwcs_s2p`, RA, Dec, CTYPE1, CTYPE2, CRVAL1, CRVAL2, CRPIX1, CRPIX2, CD1_1, CD1_2, CD2_1, CD2_2, PV1, PV2)
}

Cwcs_p2s <- function(x, y, CTYPE1, CTYPE2, CRVAL1 = 0, CRVAL2 = 0, CRPIX1 = 0, CRPIX2 = 0, CD1_1 = 1, CD1_2 = 0, CD2_1 = 0, CD2_2 = 1, PV1 = 0, PV2 = 0) {
    .Call(`_Rwcs_Cwcs_p2s`, x, y, CTYPE1, CTYPE2, CRVAL1, CRVAL2, CRPIX1, CRPIX2, CD1_1, CD1_2, CD2_1, CD2_2, PV1, PV2)
}

